perturbator-glfw3: glfw3.c ../src/libperturbator.a
	gcc -std=c99 -pedantic -Wall -Wextra -fopenmp -pthread -O3 -march=native -o perturbator-glfw3 glfw3.c -I../src -L../src -lperturbator -lGL -lGLEW -lglfw -lmpc -lmpfr -lgmp -lm -ggdb
